config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults:{format:'json'}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users
    has_many :users, through: :group_users
    validates :name, presence: true, uniqueness: true
    has_many :messages

    valiates :name. presence:true

    def show_last_message
        if(lsat_message = messages.last).present?
            last_message.content? ? last_message.content :'画像が投稿されています'
        else
            'まだメッセージがありません'
        end
    end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
    def index
        @group =Group.find(params[:group_id])
        @messages = @group.messages.includes(:user).where('id > ?',params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action:authenticate_user!
  before_action:configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupController < ApplicationController
    before_action :set_group,only:[:edit,:update]
    def index
    end

    def new
        @group = Group.new
        #部分テンプレート_group_form.html.haml内で使用するタミー変数
        #group#newがリクエストされた場合は、空の配列を渡すことでcurrent_userが二重で表示されるのを防ぐ
        @users = []
    end

    def create
        @group = Group.new(group_params)
        if @group.save
            redirect_to root_path, notice: 'グループを作成しました'
        else
            render:new
        end
    end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_group

    def index
        @message = Message.new
        @messages = @group.messages.includes(:user)
    end

    def create
        @message = @group.messages.new(message_params)
        if @message.save
            respond_to do |format|
                format.html{ redirect_to "group_messages_path(params[:group_id])"}
                format.json
            end
        else
            @messages = @group.messages.includes(:user)
            flash.now[:alert] = 'メッセージを入力してください。'
            render :index
        end
    end

    private

    def set_group
        @group = Group.find(params[:group_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def edit
    end

    def index
        @users = User.where('name LIKE(?)',"%#{params[:keyword]}#%").where.not(id: current_user.id).limit(20)
        respond_to do |format|
            format.html
            format.json
        end
    end

    def update
        if current_user.update(user_params)
            redirect_to root_path
        else
            render:edit
        end
    end

    private

    def user_params
        params.require(:user).permit(:name,:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message html.haml
.message{"data-message-id":"#{message.id}"}
    .upper-message
        .upper-message__user-name
         =message.user.name
        .upper-message__date
         =message.created_at.strftime("%Y/%m/%d %H:%M")
    .lower-message
      -if message.content.present?
        %p.lower-message__content
            =message.content
        =image_tag message.image.url,class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
%html
    %body
        = render'shared/side_bar'
        .chat
            .header
                .left-header__title
                    =@group.name
                .left-header__members
                  .members
                    - @group.users.each do |user|
                     =user.name
                .right-header
                  .right-header__btn
                    =link_to"Edit",edit_group_path(@group)
                .messages
                 =render@messages
                .form
                    = form_for [@group,@message] do |f|
                        =f.text_field:content,class:'form__message',placeholder:'type a message'
                                .form__mask
                                    =f.label:image, class:'form__mask__image' do
                                        =fa_icon'picture-o',class:'icon'
                                        =f.file_field:omage,class:'hidden'
                                    =f.submit'Send',class:'form__submit'

app/views/shared/_side_bar.html.haml
.side-bar
    .header
        %h3.header__lists
            =current_user.name
        %ul.header__lists
        %li.header__lists
            %li.link
                =link_to new_group_path do
                    =fa_icon'pencil-square-0',class:'icon'
            %li.header__lists
                =link-to edit_user_path(current_user)do
                    =fa_icon'cog',class:'icon'

    .groups
        .group
            -current_user.groups.each do|group|
                =link_to group_messages_path(group)do
                    .group__name
                    =group.name
                    .group__message
                    =group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
    .account-page__inner.clearfix
        .account-page__inner--left.account-page__header
        %h2 Edit account
        %h5 アカウントの編集
        =link_to"ログアウト"、destroy＿user＿session＿path,method: :delete, class:'btn'
        =link_to"トップページに戻る",:back,class:'btn'
        .account-page__inner--right.user-form
        =form_for(current_user) do |f|
            .field
                .field-label
                =f.label :name
                .field-input
                =f.text_field:name,autofocus:true
            .field
                .field-label
                =f.label:email
                .field-input
                =f.email_field:email

            .actions
            =f.submit"Update",class:'btn'